KOD-29.1: mappers tests
mwiski/tasks pull request #14
Opened 2019-10-14 18:50 UTC by mwiski

2019-10-15 08:32 UTC, mps4dev requested changes
:-1:

2019-10-15 08:32 UTC, mps4dev commented on src/test/java/com/crud/tasks/mapper/TaskMapperTest.java
> +        Task task = taskMapper.mapToTask(new TaskDto());
przetestuj, czy działa mapToTask(null)

2019-10-15 16:11 UTC, mwiski commented on src/test/java/com/crud/tasks/mapper/TaskMapperTest.java
> +        Task task = taskMapper.mapToTask(new TaskDto());
Nie działa, wywala NPE. W sumie chyba nie da się przekazać takiej wartości - w Postmanie mam odpowiedź, iż kolumna 'name' nie może być nullem. Mógłbym zrobić coś takiego:

Task task = taskMapper.mapToTask(new TaskDto(null, null, null));

2019-10-17 07:33 UTC, mps4dev approved these changes
:+1:

2019-10-17 15:12 UTC, merged